x-logging:
  &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100M

services:
  server:
    image: code-now-backend
    build:
      context: ./Code-Now-Backend
      dockerfile: Dockerfile
    env_file:
      - ./Code-Now-Backend/.env
    depends_on:
      - postgres-app
      - redis-app
    restart: unless-stopped

  nginx:
    image: nginx:1.25
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
      - "443:443"
    container_name: reverse_proxy
    depends_on:
      - server
    restart: unless-stopped

  postgres-app:
    image: postgres:latest
    env_file:
      - ./Code-Now-Backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis-app:
    image: redis
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis_data:/data

  judge0:
    image: judge0/judge0:1.13.1
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    ports:
      - "2358:2358"
    privileged: true
    <<: *default-logging
    restart: always

  workers:
    image: judge0/judge0:1.13.1
    command: [ "./scripts/workers" ]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    <<: *default-logging
    restart: always

  db:
    image: postgres:16.2
    env_file: judge0.conf
    volumes:
      - data:/var/lib/postgresql/data/
    <<: *default-logging
    restart: always

  redis:
    image: redis:7.2.4
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly no --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: judge0.conf
    <<: *default-logging
    restart: always

volumes:
  postgres_data:
  redis_data:
  data:
